move docker.sock to SNAP_COMMON
In a previous commit, docker runtime files were moved to SNAP_COMMON,
but /var/run/docker.sock was missed.

This commit moves docker.sock into SNAP_COMMON/var/run/docker.sock
and adds DOCKER_HOST to the environment of other apps that use
docker-cli to access dockerd.

Note we tried to use a snap layout to bind /var/run/docker.sock to
SNAP_COMMON/var/run/docker.sock instead of the more intrusive and
error prone approach in this commit, but it failed during snap install
with the following error message:

error: cannot perform the following tasks:
- Run install hook of "pelion-edge" snap if present (run hook "install":
-----
cannot update snap namespace: cannot open directory "/var/run": too many
    levels of symbolic links
snap-update-ns failed with code 1: File exists
-----)